/**
 * Dutch (nl) strings for the `umbraDesktopMultimedia` area. Same keys as `en.ts`, same reasons.
 *
 * The app names are the ones the Dutch Windows shipped where it translated them: Geluidsrecorder was,
 * Media Player never was, and the picture viewer was Windows Fotoviewer. A person looks for a tool by
 * the name their own Windows gave it.
 */
export default {
  umbraDesktopMultimedia: {
    groupMultimedia: 'Multimedia',
    mediaplayer: 'Media Player',
    pictureviewer: 'Fotoviewer',
    soundrecorder: 'Geluidsrecorder',
    volumecontrol: 'Volumeregeling',
    cdplayer: 'Cd-speler',
    mediainfo: 'Media-info',
    photoeditor: 'Foto-editor',
    camera: 'Camera',
    snippingtool: 'Knipprogramma',
    open: 'Openen…',
    openTitle: 'Openen uit de mediabibliotheek (Ctrl+O)',
    openFailed: '%0% kon niet worden geopend.',
    playerPlay: 'Afspelen',
    playerPause: 'Pauzeren',
    playerStop: 'Stoppen',
    playerMute: 'Dempen',
    playerVolume: 'Volume',
    playerSeek: 'Positie',
    playerFullScreen: 'Volledig scherm',
    playerEmpty: 'Kies Openen… om geluid of video uit de mediabibliotheek af te spelen.',
    playerNotMedia: 'Media Player speelt geluid en video af, en %0% is geen van beide.',
    playerCannotPlay: '%0% kan in deze browser niet worden afgespeeld.',
    viewerPrevious: 'Vorige afbeelding',
    viewerNext: 'Volgende afbeelding',
    viewerSlideshow: 'Diavoorstelling',
    viewerZoomIn: 'Inzoomen',
    viewerZoomOut: 'Uitzoomen',
    viewerActualSize: 'Werkelijke grootte',
    viewerFit: 'Aanpassen aan venster',
    viewerPosition: '%0% van %1%',
    viewerEmpty: 'Kies Openen… om de afbeeldingen in een mediamap te bekijken.',
    viewerNotPicture: 'Fotoviewer toont afbeeldingen, en %0% is er geen.',
    viewerCannotShow: '%0% kon niet worden weergegeven.',
    viewerNoPictures: 'In %0% staan geen afbeeldingen.',
    recorderRecord: 'Opnemen',
    recorderLive: 'Opname',
    recorderRecording: 'Opname',
    recorderName: 'Naam',
    recorderDownload: 'Downloaden',
    recorderAdd: 'Toevoegen aan Media',
    recorderAdded: 'Toegevoegd aan de mediabibliotheek.',
    recorderNotAdded: 'Niet toegevoegd. %0%',
    recorderLimit: 'Opname gestopt bij de limiet van %0%.',
    recorderDenied: 'De microfoon is niet toegestaan. Sta hem toe voor deze site in de browser en kies daarna opnieuw Opnemen.',
    recorderMissing: 'Er is geen microfoon gevonden.',
    recorderInsecure: 'De browser staat opnemen alleen toe als de backoffice via HTTPS draait.',
    recorderUnavailable: 'De microfoon kon niet worden gestart. Mogelijk gebruikt een ander programma hem.',
    volumeMaster: 'Volume',
    volumeMute: 'Dempen',
    cdEmpty: 'Kies Openen… om een mediamap met geluidsbestanden af te spelen, of één nummer en de rest van de map.',
    cdNotSound: 'Cd-speler speelt geluidsbestanden af, en %0% is er geen.',
    cdNoSound: 'In %0% staan geen geluidsbestanden.',
    cdPrevious: 'Vorig nummer',
    cdNext: 'Volgend nummer',
    cdShuffle: 'Willekeurig',
    cdRepeatOff: 'Herhalen: uit',
    cdRepeatAll: 'Herhalen: alles',
    cdRepeatOne: 'Herhalen: één',
    cdTracks: 'Nummers',
    infoEmpty: 'Kies Openen… om alles over een bestand in de mediabibliotheek te zien.',
    infoFolder: '%0% is een map. Media-info beschrijft één bestand tegelijk.',
    infoCopy: 'Kopiëren',
    infoCopied: 'Gekopieerd.',
    infoGroupFile: 'Bestand',
    infoGroupPicture: 'Afbeelding',
    infoGroupMedia: 'Geluid en video',
    infoGroupCamera: 'Camera',
    infoGroupPlace: 'Plaats',
    infoName: 'Naam',
    infoFileName: 'Bestandsnaam',
    infoMediaType: 'Mediatype',
    infoFormat: 'Indeling',
    infoSize: 'Grootte',
    infoCreated: 'Gemaakt',
    infoUpdated: 'Gewijzigd',
    infoLocation: 'Locatie',
    infoDimensions: 'Afmetingen',
    infoPixels: '%0% × %1% pixels',
    infoFocalPoint: 'Focuspunt',
    infoFocalPointValue: '%0%% van links, %1%% van boven',
    infoLength: 'Duur',
    infoCamera: 'Camera',
    infoTaken: 'Genomen',
    infoExposure: 'Belichting',
    infoAperture: 'Diafragma',
    infoIso: 'ISO',
    infoFocalLength: 'Brandpuntsafstand',
    infoCoordinates: 'Coördinaten',
    infoMap: 'Op een kaart tonen',
    editorEmpty: 'Kies Openen… om een afbeelding uit de mediabibliotheek te bewerken.',
    editorNotPicture: 'Foto-editor bewerkt afbeeldingen van pixels, en %0% is er geen.',
    editorSave: 'Opslaan',
    editorSaveAs: 'Opslaan als…',
    editorSaveTitle: 'Opslaan over de afbeelding in de mediabibliotheek (Ctrl+S)',
    editorSaveAsTitle: 'Een kopie opslaan in de mediabibliotheek',
    editorUndo: 'Ongedaan maken (Ctrl+Z)',
    editorRotateLeft: 'Linksom draaien',
    editorRotateRight: 'Rechtsom draaien',
    editorFlipHorizontal: 'Horizontaal spiegelen',
    editorFlipVertical: 'Verticaal spiegelen',
    editorCrop: 'Bijsnijden',
    editorResize: 'Formaat wijzigen',
    editorCropHint: 'Sleep over de afbeelding om te kiezen wat je wilt houden.',
    editorApplyCrop: 'Bijsnijden tot selectie',
    editorWidth: 'Breedte',
    editorHeight: 'Hoogte',
    editorKeepShape: 'Verhouding behouden',
    editorApplyResize: 'Formaat wijzigen',
    editorCancel: 'Annuleren',
    editorName: 'Naam',
    editorUntitled: 'Naamloos',
    editorSaved: 'Opgeslagen in de mediabibliotheek.',
    editorNotSaved: 'Niet opgeslagen. %0%',
    overwriteHeadline: '%0% overschrijven?',
    overwriteQuestion: '%0% is in de mediabibliotheek gewijzigd nadat je het opende. Wil je het overschrijven met jouw versie?',
    overwriteConfirm: 'Overschrijven',
    overwriteDeclined: 'Niet opgeslagen: %0% is gewijzigd in de mediabibliotheek.',
  },
};
