/** English (en) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    // app names
    appContentEditor: 'Content editor',
    appMediaLibrary: 'Media library',
    appTranslation: 'Translation',
    appDocumentTypes: 'Document Types',
    appDataTypes: 'Data Types',
    appTemplates: 'Templates',
    appUsers: 'Users',
    appMembers: 'Members',
    appLogViewer: 'Log Viewer',
    appExamineManagement: 'Examine Management',
    appHealthCheck: 'Health Check',
    appProfiling: 'Profiling',
    appSettings: 'Settings',
    appPackages: 'Packages',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    appAdvancedContentPermissions: 'Content permissions',
    appAdvancedContentAccess: 'Content access',
    appAdvancedDocTypePermissions: 'Document Type permissions',
    appAdvancedDocTypeAccess: 'Document Type access',
    appAdvancedLibraryPermissions: 'Library permissions',
    appAdvancedLibraryAccess: 'Library access',
    appAdvancedElementTypePermissions: 'Element Type permissions',
    appAdvancedElementTypeAccess: 'Element Type access',
    appWorkflowTasks: 'Workflow tasks',
    appWorkflowSearch: 'Workflow search',
    appWorkflowReleaseSets: 'Release sets',
    appDeploy: 'Deploy',
    appDeployEnvironments: 'Deploy environments',
    appDeployStatus: 'Deploy status',
    appDeploySchema: 'Deploy schema',
    appDeployConfiguration: 'Deploy configuration',
    appEngageConfiguration: 'Engage configuration',
    appBackgroundJobs: 'Background Jobs',
    // window body: a registered app's element failed to load (app-host.element carries the same
    // English as its own fallback, for the case where this dictionary is what failed to load).
    appLoadFailed: 'This app could not be loaded.',
    // group labels
    groupEditing: 'Editing',
    groupWorkflow: 'Workflow',
    groupMarketingSales: 'Marketing and sales',
    groupDevelopment: 'Development',
    groupSynchronisation: 'Synchronisation',
    groupSecurity: 'Security',
    groupAdvancedSecurity: 'Advanced security',
    groupDiagnostics: 'Diagnostics',
    groupAutomation: 'Automation',
    groupAi: 'AI',
    groupSystem: 'System',
    groupGames: 'Games',
    groupMore: 'More',
    // header-app launcher
    launchDesktop: 'Open desktop',
    // launcher chrome
    openApps: 'Open apps',
    search: 'Search apps, tools and content…',
    favourites: 'Pinned',
    recent: 'Recent',
    pin: 'Pin to top',
    unpin: 'Unpin',
    desktopSettings: 'Desktop settings',
    // desktop settings — theme
    theme: 'Theme',
    themeDescription: 'Changes the look of the desktop, taskbar and windows. Your content stays the same.',
    themeHighContrast:
      "The backoffice is in high contrast. Window content follows it; the desktop keeps this theme's darkest palette.",
    themePickerTitle: 'Choose a theme',
    wallpaperFollowsTheme: 'Match the wallpaper to the theme',
    // desktop settings — the backoffice's own theme, which is Umbraco's setting rather than ours.
    // Named for what it changes, because the row above it is already called Theme.
    backofficeTheme: 'Backoffice colours',
    backofficeThemeAbout: "Umbraco's own light, dark and high contrast. Applies to the whole backoffice, including what is inside every window.",
    backofficeThemePickerTitle: 'Choose backoffice colours',
    // one sentence per theme, shown beside its preview in the picker: what it *is*, not what it does
    themeAboutUmbraco: "The desktop as it ships, built from Umbraco's own colours and spacing.",
    themeAboutUmbraco4: 'The 2009 backoffice as desktop chrome: warm grey gradients, hairline panels and buttons that press in.',
    themeAboutMacos: 'Traffic lights on the left of every title bar, a floating dock, and a fullscreen blurred launcher.',
    themeAboutWin11: 'A flush acrylic taskbar with its buttons centred, rounded windows and square caption buttons.',
    themeAboutWin98: 'Grey everywhere, double bevels, square corners, a navy title bar and a Start menu.',
    // desktop settings — the categories the panel is divided into, and the line under each
    groupAppearance: 'Appearance',
    groupGeneral: 'General',
    groupLanguage: 'Language and region',
    groupTaskbar: 'Taskbar',
    groupAppearanceAbout: 'The theme and the wallpaper behind your windows',
    groupGeneralAbout: 'How the desktop starts, and where you land when you sign in',
    groupLanguageAbout: 'The language the backoffice speaks, and how the desktop writes dates and times',
    groupTaskbarAbout: 'What the taskbar keeps beside the launcher button',
    groupSite: 'Site',
    groupSiteAbout: 'Settings that apply to everyone on this site, not just to you',
    siteAppIcon: 'App icon',
    siteAppIconAbout:
      'The icon this site gets when someone installs the backoffice as an app. Everyone sees the same one.',
    siteAppIconDefault: 'UmbraDesktop',
    siteAppIconGuidance:
      'A square PNG of at least 512×512. It is cropped to a square and shrunk to 32px on a taskbar, so keep it simple and avoid small text. Transparency is fine; the corners may be rounded or cut to a circle by the operating system, so keep anything important away from the edges.',
    siteAppIconPreview: 'What it will look like',
    siteAppIconCustom: 'Choose an image',
    siteAppIconChoose: 'Choose an image…',
    siteAppName: 'App name',
    siteAppNameAbout:
      "What the installed app is called. Leave empty to use this site's own name.",
    siteLockedByConfiguration: 'Set in appsettings.json, so it cannot be changed here.',
    // desktop settings — taskbar. The switches are grouped by which end of the bar they are about,
    // because a screen that opens on a bare "AI chat" switch never says what it is a setting for.
    taskbarRegionLauncher: 'Taskbar items',
    taskbarRegionLauncherAbout:
      'Buttons beside the launcher button, in this order. Each one opens an app, the way the launcher does. Switching between the windows you already have stays with the buttons further along the bar.',
    taskbarRegionTray: 'System tray icons',
    taskbarRegionTrayAbout: 'Icons beside the clock, which report on things rather than open them.',
    // One switch per feature. The line under it says what the feature puts on the taskbar, and a
    // feature that cannot be switched on here says why underneath that.
    taskbarAiChat: 'AI chat',
    taskbarAiChatAbout: 'Puts a button for the Copilot Workspace at the start of the taskbar.',
    taskbarAiChatNotInstalled: 'Umbraco AI is not installed on this site, so there is no chat to open.',
    taskbarAiChatNoPermission: 'You do not have access to the AI section, so the chat cannot be opened from here.',
    taskbarPinnedApps: 'Pinned apps',
    taskbarPinnedAppsAbout:
      'Shows the apps you pinned in the launcher on the taskbar too, in the same order. Pin and unpin in the launcher as you always have.',
    settingsCategoryLoadFailed: 'This category could not be loaded.',
    settingsBack: 'Back to Desktop settings',
    // desktop settings — startup
    bootIntoDesktop: 'Open the desktop when I sign in',
    bootDescription:
      'Takes effect the next time you open the backoffice, not right now. A link straight to a document still opens that document. Add ?desktop=off to the backoffice address to skip it once.',
    // desktop settings — language and region. The first row is the odd one out and its hint says so:
    // it changes the whole backoffice, and it is the only setting here that needs a reload.
    backofficeLanguage: 'Backoffice language',
    backofficeLanguageAbout:
      "Changes the language of the whole backoffice, not just the desktop. You'll be asked to reload.",
    regionalFormat: 'Regional format',
    regionalFormatAbout:
      'How the desktop writes dates and times. Your backoffice language and your browser can disagree about this.',
    formatBackoffice: 'Match the backoffice language',
    formatBrowser: 'Match my browser',
    clock: 'Clock',
    clockAuto: 'Automatic',
    clock12: '12 hour',
    clock24: '24 hour',
    clockPreview: 'The taskbar will show',
    // The reload the language change needs. It closes every open window, not only unsaved ones,
    // because nothing here restores a session.
    reloadHeadline: 'Reload the desktop?',
    reloadSaved: 'Your language is saved. The desktop has to reload before it takes effect.',
    reloadClosesOne: 'This closes your open window.',
    reloadCloses: 'This closes your %0% open windows.',
    reloadQuestion: 'Reload now?',
    reloadConfirm: 'Reload now',
    reloadLater: 'Later',
    // desktop settings — wallpaper
    wallpaper: 'Wallpaper',
    wallpaperNone: 'None (gradient)',
    wallpaperBuiltIn: 'Built-in image',
    wallpaperFromMedia: 'From the Media Library',
    wallpaperOwnImage: 'Your own image',
    wallpaperOwnImageChange: 'Click to pick another',
    wallpaperMediaLibrary: 'Media library',
    wallpaperPickerTitle: 'Choose a wallpaper',
    wallpaperNotAnImage: 'That file cannot be used as a wallpaper. Pick an image.',
    logout: 'Log out',
    exitDesktop: 'Exit desktop',
    // exiting the desktop
    exitHeadline: 'Exit desktop mode',
    exitQuestion: 'Return to the classic Umbraco backoffice? Your open windows will be closed.',
    exitConfirm: 'Exit',
    exitStay: 'Stay',
    // path strip
    pathLabel: 'Location',
    // unsaved changes
    unsavedChanges: 'Unsaved changes',
    exitUnsavedOne: 'One window has unsaved changes, which will be discarded.',
    exitUnsaved: '%0% windows have unsaved changes, which will be discarded.',
    exitConflictedSole: 'That window has also been changed by someone else.',
    exitConflictedOne: 'One of them has also been changed by someone else.',
    exitConflictedMany: '%0% of them have also been changed by someone else.',
    // changed, trashed or deleted underneath a window
    noticeChangedTitle: 'Someone else changed this while you were editing it',
    noticeChangedBody: 'Saving now replaces their version with yours.',
    noticeTrashedTitle: 'Someone moved this to the recycle bin',
    noticeTrashedBody:
      'Items in the recycle bin are read-only, so this window will stop accepting changes as soon as it reloads. Copy anything you need now, or ask someone to restore it.',
    noticeDeletedTitle: 'This no longer exists',
    noticeDeletedBody: 'Someone deleted it permanently.',
    noticeDeletedDirtyBody:
      'Someone deleted it permanently. Your unsaved changes cannot be saved, because there is nothing left to save them to. Copy anything you need before you close this window.',
    noticeKeepMine: 'Keep my changes',
    // Short enough to sit beside "Keep my changes" without the banner reading as clutter. The full
    // sentence is `noticeChangedBody`'s job, and repeating it on the button was a large part of why
    // the bar looked busy.
    noticeDiscardMine: 'Discard mine, load theirs',
    noticeCloseWindow: 'Close window',
    noticeKeepHeadline: 'Keep your changes?',
    noticeKeepQuestion:
      'When you save, the changes the other person made will be lost. This window will keep warning you until you save or discard.',
    noticeKeepConfirm: 'Keep my changes',
    noticeAcknowledged: 'Changed by someone else',
    discardConflictedHeadline: 'Close this window?',
    discardConflictedQuestion:
      'Closing is the safe option here: your unsaved changes are discarded and the version someone else saved is kept.',
    // Background Jobs app
    backgroundJobsIntro:
      'Every scheduled job Umbraco runs behind your site: publishing, webhooks, cleanups, and anything a package added. Nothing here can be started or stopped, it is a read-only view of what the CMS is doing on its own.',
    backgroundJobsName: 'Name',
    backgroundJobsPeriod: 'Every',
    backgroundJobsLastRun: 'Last run',
    backgroundJobsLastOutcome: 'Outcome',
    backgroundJobsNextRun: 'Next run',
    backgroundJobsRunsOn: 'Runs on',
    backgroundJobsKindDistributed: 'Distributed',
    backgroundJobsKindRecurring: 'Recurring',
    backgroundJobsDistributedNote:
      'Shared across every server. Each run is claimed by one server, and the schedule is stored in the database, so it survives a restart. Umbraco does not record how a run ended, so there is no outcome to show.',
    backgroundJobsRecurringNote:
      'Run by each server for itself. Umbraco stores nothing about them, so what you see here has been observed since this server started.',
    backgroundJobsJobCountOne: '1 job',
    backgroundJobsJobCount: '%0% jobs',
    backgroundJobsStateRunning: 'Running',
    backgroundJobsStateStale: 'Stale',
    backgroundJobsStateManual: 'Manual',
    backgroundJobsOutcomeUnavailable: 'Not recorded by Umbraco',
    backgroundJobsOutcomeNotObserved: 'Not since restart',
    backgroundJobsOutcomeSucceeded: 'Succeeded',
    backgroundJobsOutcomeFailed: 'Failed',
    backgroundJobsOutcomeIgnored: 'Skipped on this server',
    backgroundJobsNeverRun: 'Not since restart',
    backgroundJobsDueNow: 'Due now',
    backgroundJobsAnyServer: 'Any server',
    backgroundJobsRoleUnknown: 'Unknown role',
    backgroundJobsRoleSingle: 'Single server',
    backgroundJobsRoleSchedulingPublisher: 'Scheduling publisher',
    backgroundJobsRoleSubscriber: 'Subscriber',
    backgroundJobsMonitoringSince: 'Monitoring since %0%',
    backgroundJobsRefreshingEveryOne: 'Refreshing every second',
    backgroundJobsRefreshingEvery: 'Refreshing every %0% seconds',
    backgroundJobsIntervalOne: 'Every second',
    backgroundJobsInterval: 'Every %0% seconds',
    backgroundJobsChooseInterval: 'Choose how often this refreshes',
    backgroundJobsLoadFailed: 'Could not load background jobs.',
    backgroundJobsRetrying: 'Retrying automatically.',
    backgroundJobsRefreshFailed: 'The last refresh failed. Showing the previous result.',
    backgroundJobsEmpty: 'No background jobs are registered on this server.',
    // connections to other Umbraco instances. Called connections and not environments on purpose:
    // an environment in Umbraco means test, acceptance and production of one solution, which is a
    // different feature with its own issues, and these are unrelated instances.
    groupConnections: 'Connections (experimental)',
    groupConnectionsAbout: 'Other Umbraco instances this desktop can read from',
    groupExperimental: 'Experimental',
    connectionsAbout:
      'Add an Umbraco instance by giving it an API user. Nothing is installed on that instance, and the desktop only ever reads from it.',
    connectionsExperimental:
      'This is experimental. It works, but how connections are configured and what they can read is still likely to change, so expect to redo some of this in a later version.',
    connectionClientIdAbout:
      'Create an API user in the other instance’s backoffice, under Users, and paste its client ID here. Nothing is installed there, and whoever owns that instance can revoke it at any time.',
    connectionClientSecretAbout:
      'The secret shown when that API user was created. The status app needs no sections at all, so the smallest possible user group is enough.',
    connectionsEmpty: 'No instances are connected yet.',
    connectionAdd: 'Add an instance',
    connectionEditHeadline: 'Edit instance',
    connectionEdit: 'Edit',
    connectionRemove: 'Remove',
    connectionRemoveHeadline: 'Remove instance',
    connectionRemoveConfirm: 'Remove %0% and the credentials stored for it?',
    connectionSave: 'Save',
    connectionCancel: 'Cancel',
    connectionName: 'Name',
    connectionNameAbout: 'What you call this instance. The client name, usually.',
    connectionUrl: 'Address',
    connectionUrlAbout: 'The site address, without a path. For example https://www.example.com',
    connectionUrlInvalid:
      'That is not a web address the desktop can use. It has to start with https:// or http://, and a port cannot be higher than 65535.',
    connectionColour: 'Colour',
    connectionColourAbout: 'Tells this instance apart from the others at a glance.',
    connectionClientId: 'Client ID',
    connectionClientSecret: 'Client secret',
    connectionSecretStored: 'A secret is stored. Leave this blank to keep it.',
    connectionSecretMissing: 'No secret stored yet, so this instance cannot be read.',
    connectionSecretWriteOnly: 'Once saved, a secret can be replaced but never read back.',
    // the five outcomes, worded as what to do about them rather than as error codes
    connectionStateChecking: 'Checking\u2026',
    connectionStateOk: 'Connected',
    connectionStateUnreachable: 'Cannot be reached',
    connectionStateInvalidCredentials: 'Credentials refused',
    connectionStateForbidden: 'Not permitted',
    connectionStateNotConfigured: 'No secret set',
    // status app
    appConnectionStatus: 'Connection status',
    connectionStatusAbout: 'Every instance this desktop is connected to, and what it reports about itself.',
    connectionStatusConnection: 'Connection',
    connectionStatusGroupLocal: 'This instance',
    connectionStatusGroupRemote: 'Connected instances',
    connectionStatusVersion: 'Umbraco version',
    connectionStatusMode: 'Runtime mode',
    connectionStatusRuntime: 'State',
    connectionStatusUnknown: 'Unknown',
    connectionStatusManage: 'Manage connections',
    connectionStatusRefresh: 'Refresh',
    connectionStatusLoadFailed: 'Could not read the connection status.',
    // the permission card, shown in place of whatever could not be read
    permissionNeeded: 'Permission needed',
    permissionNeededRemote:
      "The API user on %0% may not read this. Someone with access to that instance can put it in a group that has the section it needs.",
    permissionNeededLocal:
      'Managing connections needs access to the Settings section here. Ask an administrator of this instance.',
  },
};
