/** Dutch (nl) strings for the `umbraDesktop` area — launcher chrome, friendly app names, and group labels. */
export default {
  umbraDesktop: {
    appContentEditor: 'Content-editor',
    appMediaLibrary: 'Mediabibliotheek',
    appTranslation: 'Vertaling',
    appDocumentTypes: 'Documenttypes',
    appDataTypes: 'Datatypes',
    appTemplates: 'Templates',
    appUsers: 'Gebruikers',
    appMembers: 'Leden',
    appLogViewer: 'Logboek',
    appExamineManagement: 'Examine-beheer',
    appHealthCheck: 'Gezondheidscontrole',
    appProfiling: 'Profilering',
    appSettings: 'Instellingen',
    appPackages: 'Pakketten',
    appModelsBuilder: 'Models Builder',
    appWebhooks: 'Webhooks',
    appAdvancedContentPermissions: 'Inhoudsmachtigingen',
    appAdvancedContentAccess: 'Inhoudstoegang',
    appAdvancedDocTypePermissions: 'Documenttype-machtigingen',
    appAdvancedDocTypeAccess: 'Documenttype-toegang',
    appAdvancedLibraryPermissions: 'Library-machtigingen',
    appAdvancedLibraryAccess: 'Library-toegang',
    appAdvancedElementTypePermissions: 'Elementtype-machtigingen',
    appAdvancedElementTypeAccess: 'Elementtype-toegang',
    appWorkflowTasks: 'Workflow-taken',
    appWorkflowSearch: 'Workflow-zoeken',
    appWorkflowReleaseSets: 'Release sets',
    appDeploy: 'Deploy',
    appDeployEnvironments: 'Deploy-omgevingen',
    appDeployStatus: 'Deploy-status',
    appDeploySchema: 'Deploy-schema',
    appDeployConfiguration: 'Deploy-configuratie',
    appEngageConfiguration: 'Engage-configuratie',
    appBackgroundJobs: 'Achtergrondtaken',
    appLoadFailed: 'Deze app kon niet worden geladen.',
    groupEditing: 'Bewerken',
    groupWorkflow: 'Workflow',
    groupMarketingSales: 'Marketing en verkoop',
    groupDevelopment: 'Ontwikkeling',
    groupSynchronisation: 'Synchronisatie',
    groupSecurity: 'Beveiliging',
    groupAdvancedSecurity: 'Geavanceerde beveiliging',
    groupDiagnostics: 'Diagnostiek',
    groupAutomation: 'Automatisering',
    groupAi: 'AI',
    groupSystem: 'Systeem',
    groupGames: 'Spellen',
    groupMore: 'Meer',
    launchDesktop: 'Bureaublad openen',
    openApps: 'Apps openen',
    search: 'Zoek apps, tools en content…',
    favourites: 'Vastgezet',
    recent: 'Recent',
    pin: 'Bovenaan vastzetten',
    unpin: 'Losmaken',
    desktopSettings: 'Bureaublad-instellingen',
    // desktop settings — theme
    theme: 'Thema',
    themeDescription: 'Verandert het uiterlijk van het bureaublad, de taakbalk en de vensters. Je content blijft hetzelfde.',
    themeHighContrast:
      'De backoffice staat op hoog contrast. De vensterinhoud volgt dat; het bureaublad houdt het donkerste palet van dit thema aan.',
    themePickerTitle: 'Kies een thema',
    wallpaperFollowsTheme: 'Achtergrond bij het thema laten passen',
    // bureaubladinstellingen — het thema van de backoffice zelf: een instelling van Umbraco, niet
    // van ons. Genoemd naar wat het verandert, want de rij erboven heet al Thema.
    backofficeTheme: 'Backoffice-kleuren',
    backofficeThemeAbout: 'Het lichte, donkere en hoog-contrastthema van Umbraco zelf. Geldt voor de hele backoffice, dus ook voor wat er in elk venster staat.',
    backofficeThemePickerTitle: 'Kies backoffice-kleuren',
    // één zin per thema, naast de voorvertoning in de kiezer: wat het *is*, niet wat het doet
    themeAboutUmbraco: 'Het bureaublad zoals het standaard is, opgebouwd uit de kleuren en maatvoering van Umbraco zelf.',
    themeAboutUmbraco4: 'De backoffice van 2009 als vensterrand: warmgrijze verlopen, haarfijne panelen en knoppen die indrukken.',
    themeAboutMacos: 'Stoplichten links in elke titelbalk, een zwevend dock en een schermvullende, vervaagde launcher.',
    themeAboutWin11: 'Een vlakke acryl-taakbalk met gecentreerde knoppen, afgeronde vensters en vierkante titelknoppen.',
    themeAboutWin98: 'Overal grijs, dubbele randen, vierkante hoeken, een marineblauwe titelbalk en een Startmenu.',
    // desktop settings — de categorieën waarin het paneel is verdeeld, en de regel onder elke rij
    groupAppearance: 'Weergave',
    groupGeneral: 'Algemeen',
    groupLanguage: 'Taal en regio',
    groupTaskbar: 'Taakbalk',
    groupAppearanceAbout: 'Het thema en de achtergrond achter je vensters',
    groupGeneralAbout: 'Hoe het bureaublad start en waar je terechtkomt als je inlogt',
    groupLanguageAbout: 'De taal van de backoffice, en hoe het bureaublad datums en tijden schrijft',
    groupTaskbarAbout: 'Wat de taakbalk naast de startknop bewaart',
    groupSite: 'Site',
    groupSiteAbout: 'Instellingen die voor iedereen op deze site gelden, niet alleen voor jou',
    siteAppIcon: 'App-pictogram',
    siteAppIconAbout:
      'Het pictogram dat deze site krijgt wanneer iemand de backoffice als app installeert. Iedereen ziet hetzelfde.',
    siteAppIconDefault: 'UmbraDesktop',
    siteAppIconGuidance:
      'Een vierkante PNG van minstens 512×512. De afbeelding wordt vierkant bijgesneden en op een taakbalk tot 32px verkleind, dus houd hem eenvoudig en vermijd kleine tekst. Transparantie mag; het besturingssysteem kan de hoeken afronden of er een cirkel van maken, dus houd belangrijke details weg bij de randen.',
    siteAppIconPreview: 'Hoe het eruit komt te zien',
    siteAppIconCustom: 'Kies een afbeelding',
    siteAppIconChoose: 'Kies een afbeelding…',
    siteAppName: 'Appnaam',
    siteAppNameAbout:
      'Hoe de geïnstalleerde app heet. Laat leeg om de naam van deze site te gebruiken.',
    siteLockedByConfiguration: 'Ingesteld in appsettings.json en hier dus niet te wijzigen.',
    // bureaubladinstellingen — taakbalk. De schakelaars staan gegroepeerd per kant van de balk,
    // omdat een scherm dat begint met een kale "AI-chat"-schakelaar nergens zegt waar het over gaat.
    taskbarRegionLauncher: 'Taakbalkonderdelen',
    taskbarRegionLauncherAbout:
      'Knoppen naast de startknop, in deze volgorde. Elke knop opent een app, net als de launcher. Wisselen tussen de vensters die al open staan blijft bij de knoppen verderop in de balk.',
    taskbarRegionTray: 'Systeemvakpictogrammen',
    taskbarRegionTrayAbout: 'Pictogrammen naast de klok, die iets melden in plaats van iets openen.',
    // Eén schakelaar per onderdeel. De regel eronder vertelt wat het onderdeel op de taakbalk zet;
    // een onderdeel dat hier niet aangezet kan worden, zegt daaronder waarom niet.
    taskbarAiChat: 'AI-chat',
    taskbarAiChatAbout: 'Zet vooraan op de taakbalk een knop voor de Copilot Workspace.',
    taskbarAiChatNotInstalled: 'Umbraco AI is niet op deze site geïnstalleerd, dus er is geen chat om te openen.',
    taskbarAiChatNoPermission: 'Je hebt geen toegang tot de AI-sectie, dus de chat kan hier niet worden geopend.',
    taskbarPinnedApps: 'Vastgezette apps',
    taskbarPinnedAppsAbout:
      'Toont de apps die je in de launcher hebt vastgezet ook op de taakbalk, in dezelfde volgorde. Vastzetten en losmaken doe je in de launcher, zoals altijd.',
    settingsCategoryLoadFailed: 'Deze categorie kon niet worden geladen.',
    settingsBack: 'Terug naar bureaubladinstellingen',
    // desktop settings — startup
    bootIntoDesktop: 'Open het bureaublad als ik inlog',
    bootDescription:
      'Werkt vanaf de volgende keer dat je de backoffice opent, niet direct. Een link rechtstreeks naar een document opent nog steeds dat document. Zet ?desktop=off achter het backoffice-adres om het één keer over te slaan.',
    // bureaubladinstellingen — taal en regio. De eerste rij is de vreemde eend en de regel eronder
    // zegt dat ook: die verandert de hele backoffice en is de enige die opnieuw laden vraagt.
    backofficeLanguage: 'Taal van de backoffice',
    backofficeLanguageAbout:
      'Verandert de taal van de hele backoffice, niet alleen van het bureaublad. Je wordt gevraagd opnieuw te laden.',
    regionalFormat: 'Regionale notatie',
    regionalFormatAbout:
      'Hoe het bureaublad datums en tijden schrijft. Je backoffice-taal en je browser kunnen hierover van mening verschillen.',
    formatBackoffice: 'Volg de taal van de backoffice',
    formatBrowser: 'Volg mijn browser',
    clock: 'Klok',
    clockAuto: 'Automatisch',
    clock12: '12 uur',
    clock24: '24 uur',
    clockPreview: 'De taakbalk toont',
    // Het opnieuw laden dat de taalwijziging nodig heeft. Dat sluit elk open venster, niet alleen de
    // vensters met niet-opgeslagen wijzigingen, want een sessie wordt hier nergens hersteld.
    reloadHeadline: 'Bureaublad opnieuw laden?',
    reloadSaved: 'Je taal is opgeslagen. Het bureaublad moet opnieuw laden voordat dit werkt.',
    reloadClosesOne: 'Hiermee sluit je je openstaande venster.',
    reloadCloses: 'Hiermee sluit je je %0% openstaande vensters.',
    reloadQuestion: 'Nu opnieuw laden?',
    reloadConfirm: 'Nu opnieuw laden',
    reloadLater: 'Later',
    // desktop settings — wallpaper
    wallpaper: 'Achtergrond',
    wallpaperNone: 'Geen (verloop)',
    wallpaperBuiltIn: 'Meegeleverde afbeelding',
    wallpaperFromMedia: 'Uit de Media-bibliotheek',
    wallpaperOwnImage: 'Je eigen afbeelding',
    wallpaperOwnImageChange: 'Klik om een andere te kiezen',
    wallpaperMediaLibrary: 'Media-bibliotheek',
    wallpaperPickerTitle: 'Kies een achtergrond',
    wallpaperNotAnImage: 'Dit bestand kan niet als achtergrond worden gebruikt. Kies een afbeelding.',
    logout: 'Uitloggen',
    exitDesktop: 'Bureaublad verlaten',
    // bureaublad verlaten
    exitHeadline: 'Bureaublad verlaten',
    exitQuestion: 'Terug naar de klassieke Umbraco-backoffice? Je open vensters worden gesloten.',
    exitConfirm: 'Verlaten',
    exitStay: 'Blijven',
    // padbalk
    pathLabel: 'Locatie',
    // niet-opgeslagen wijzigingen
    unsavedChanges: 'Niet-opgeslagen wijzigingen',
    exitUnsavedOne: 'In één venster staan niet-opgeslagen wijzigingen, die verloren gaan.',
    exitUnsaved: 'In %0% vensters staan niet-opgeslagen wijzigingen, die verloren gaan.',
    exitConflictedSole: 'Dat venster is ook door iemand anders gewijzigd.',
    exitConflictedOne: 'Eén daarvan is ook door iemand anders gewijzigd.',
    exitConflictedMany: '%0% daarvan zijn ook door iemand anders gewijzigd.',
    // gewijzigd, in de prullenbak of verwijderd onder een venster
    noticeChangedTitle: 'Iemand anders heeft dit gewijzigd terwijl je eraan werkte',
    noticeChangedBody: 'Als je nu opslaat, vervang je hun versie door de jouwe.',
    noticeTrashedTitle: 'Iemand heeft dit naar de prullenbak verplaatst',
    noticeTrashedBody:
      'Items in de prullenbak zijn alleen-lezen, dus dit venster accepteert geen wijzigingen meer zodra het herlaadt. Kopieer nu wat je nodig hebt, of vraag iemand om het terug te zetten.',
    noticeDeletedTitle: 'Dit bestaat niet meer',
    noticeDeletedBody: 'Iemand heeft het definitief verwijderd.',
    noticeDeletedDirtyBody:
      'Iemand heeft het definitief verwijderd. Je niet-opgeslagen wijzigingen kunnen niet worden opgeslagen, want er is niets meer om ze in op te slaan. Kopieer wat je nodig hebt voordat je dit venster sluit.',
    noticeKeepMine: 'Mijn wijzigingen behouden',
    noticeDiscardMine: 'Mijn wijzigingen weggooien, die van hen laden',
    noticeCloseWindow: 'Venster sluiten',
    noticeKeepHeadline: 'Je wijzigingen behouden?',
    noticeKeepQuestion:
      'Als je opslaat, gaan de wijzigingen van de ander verloren. Dit venster blijft waarschuwen tot je opslaat of weggooit.',
    noticeKeepConfirm: 'Mijn wijzigingen behouden',
    noticeAcknowledged: 'Door iemand anders gewijzigd',
    discardConflictedHeadline: 'Dit venster sluiten?',
    discardConflictedQuestion:
      'Sluiten is hier de veilige keuze: je niet-opgeslagen wijzigingen gaan verloren en de versie die iemand anders heeft opgeslagen blijft staan.',
    // Background Jobs app
    backgroundJobsIntro:
      'Alle geplande taken die Umbraco achter je site uitvoert: publiceren, webhooks, opschoningen, en alles wat een pakket heeft toegevoegd. Je kunt hier niets starten of stoppen, dit is een alleen-lezen overzicht van wat het CMS uit zichzelf doet.',
    backgroundJobsName: 'Naam',
    backgroundJobsPeriod: 'Elke',
    backgroundJobsLastRun: 'Laatste uitvoering',
    backgroundJobsLastOutcome: 'Resultaat',
    backgroundJobsNextRun: 'Volgende uitvoering',
    backgroundJobsRunsOn: 'Draait op',
    backgroundJobsKindDistributed: 'Gedistribueerd',
    backgroundJobsKindRecurring: 'Terugkerend',
    backgroundJobsDistributedNote:
      'Gedeeld over alle servers. Elke uitvoering wordt door één server geclaimd en het schema staat in de database, dus het overleeft een herstart. Umbraco legt niet vast hoe een uitvoering is afgelopen, dus er is geen resultaat om te tonen.',
    backgroundJobsRecurringNote:
      'Wordt door elke server voor zichzelf uitgevoerd. Umbraco slaat hier niets over op, dus wat je hier ziet is waargenomen sinds deze server is gestart.',
    backgroundJobsJobCountOne: '1 taak',
    backgroundJobsJobCount: '%0% taken',
    backgroundJobsStateRunning: 'Actief',
    backgroundJobsStateStale: 'Vastgelopen',
    backgroundJobsStateManual: 'Handmatig',
    backgroundJobsOutcomeUnavailable: 'Niet vastgelegd door Umbraco',
    backgroundJobsOutcomeNotObserved: 'Nog niet sinds herstart',
    backgroundJobsOutcomeSucceeded: 'Geslaagd',
    backgroundJobsOutcomeFailed: 'Mislukt',
    backgroundJobsOutcomeIgnored: 'Overgeslagen op deze server',
    backgroundJobsNeverRun: 'Nog niet sinds herstart',
    backgroundJobsDueNow: 'Nu aan de beurt',
    backgroundJobsAnyServer: 'Elke server',
    backgroundJobsRoleUnknown: 'Onbekende rol',
    backgroundJobsRoleSingle: 'Enkele server',
    backgroundJobsRoleSchedulingPublisher: 'Scheduling publisher',
    backgroundJobsRoleSubscriber: 'Subscriber',
    backgroundJobsMonitoringSince: 'Bewaakt sinds %0%',
    backgroundJobsRefreshingEveryOne: 'Ververst elke seconde',
    backgroundJobsRefreshingEvery: 'Ververst elke %0% seconden',
    backgroundJobsIntervalOne: 'Elke seconde',
    backgroundJobsInterval: 'Elke %0% seconden',
    backgroundJobsChooseInterval: 'Kies hoe vaak dit ververst',
    backgroundJobsLoadFailed: 'Achtergrondtaken konden niet worden geladen.',
    backgroundJobsRetrying: 'Wordt automatisch opnieuw geprobeerd.',
    backgroundJobsRefreshFailed: 'De laatste verversing is mislukt. Het vorige resultaat wordt getoond.',
    backgroundJobsEmpty: 'Er zijn geen achtergrondtaken geregistreerd op deze server.',
    // verbindingen met andere Umbraco-installaties. Bewust verbindingen en geen omgevingen: een
    // omgeving betekent in Umbraco test, acceptatie en productie van een oplossing, en dat is een
    // andere functie met eigen issues. Dit zijn losstaande installaties.
    groupConnections: 'Verbindingen (experimenteel)',
    groupConnectionsAbout: 'Andere Umbraco-installaties die dit bureaublad mag lezen',
    groupExperimental: 'Experimenteel',
    connectionsAbout:
      'Voeg een Umbraco-installatie toe door er een API-gebruiker voor aan te maken. Op die installatie wordt niets geïnstalleerd, en het bureaublad leest er alleen uit.',
    connectionsExperimental:
      'Dit is experimenteel. Het werkt, maar hoe verbindingen worden ingesteld en wat ze mogen lezen verandert waarschijnlijk nog, dus houd er rekening mee dat je dit in een latere versie deels opnieuw moet doen.',
    connectionClientIdAbout:
      'Maak in de backoffice van de andere installatie een API-gebruiker aan, onder Gebruikers, en plak hier het client-ID. Daar wordt niets geïnstalleerd, en de eigenaar van die installatie kan de toegang op elk moment intrekken.',
    connectionClientSecretAbout:
      'Het geheim dat werd getoond toen die API-gebruiker werd aangemaakt. De statusapp heeft geen enkele sectie nodig, dus de kleinst mogelijke gebruikersgroep volstaat.',
    connectionsEmpty: 'Er zijn nog geen installaties verbonden.',
    connectionAdd: 'Installatie toevoegen',
    connectionEditHeadline: 'Installatie bewerken',
    connectionEdit: 'Bewerken',
    connectionRemove: 'Verwijderen',
    connectionRemoveHeadline: 'Installatie verwijderen',
    connectionRemoveConfirm: '%0% en de opgeslagen inloggegevens verwijderen?',
    connectionSave: 'Opslaan',
    connectionCancel: 'Annuleren',
    connectionName: 'Naam',
    connectionNameAbout: 'Hoe jij deze installatie noemt. Meestal de naam van de klant.',
    connectionUrl: 'Adres',
    connectionUrlAbout: 'Het adres van de site, zonder pad. Bijvoorbeeld https://www.example.com',
    connectionUrlInvalid:
      'Dit is geen webadres dat het bureaublad kan gebruiken. Het moet beginnen met https:// of http://, en een poort kan niet hoger zijn dan 65535.',
    connectionColour: 'Kleur',
    connectionColourAbout: 'Hiermee herken je deze installatie in één oogopslag tussen de andere.',
    connectionClientId: 'Client-ID',
    connectionClientSecret: 'Clientgeheim',
    connectionSecretStored: 'Er is een geheim opgeslagen. Laat dit leeg om het te behouden.',
    connectionSecretMissing: 'Nog geen geheim opgeslagen, dus deze installatie kan niet gelezen worden.',
    connectionSecretWriteOnly: 'Een opgeslagen geheim kan vervangen worden, maar nooit meer uitgelezen.',
    // de vijf uitkomsten, geformuleerd als wat je eraan kunt doen in plaats van als foutcodes
    connectionStateChecking: 'Bezig met controleren\u2026',
    connectionStateOk: 'Verbonden',
    connectionStateUnreachable: 'Niet bereikbaar',
    connectionStateInvalidCredentials: 'Inloggegevens geweigerd',
    connectionStateForbidden: 'Geen toegang',
    connectionStateNotConfigured: 'Geen geheim ingesteld',
    // statusapp
    appConnectionStatus: 'Verbindingsstatus',
    connectionStatusAbout: 'Elke installatie waarmee dit bureaublad verbonden is, en wat die over zichzelf meldt.',
    connectionStatusConnection: 'Verbinding',
    connectionStatusGroupLocal: 'Deze installatie',
    connectionStatusGroupRemote: 'Verbonden installaties',
    connectionStatusVersion: 'Umbraco-versie',
    connectionStatusMode: 'Runtime-modus',
    connectionStatusRuntime: 'Status',
    connectionStatusUnknown: 'Onbekend',
    connectionStatusManage: 'Verbindingen beheren',
    connectionStatusRefresh: 'Verversen',
    connectionStatusLoadFailed: 'De verbindingsstatus kon niet gelezen worden.',
    // de toestemmingskaart, getoond in plaats van wat niet gelezen kon worden
    permissionNeeded: 'Toestemming nodig',
    permissionNeededRemote:
      'De API-gebruiker op %0% mag dit niet lezen. Iemand met toegang tot die installatie kan de gebruiker in een groep zetten die de benodigde sectie heeft.',
    permissionNeededLocal:
      'Verbindingen beheren vereist toegang tot de sectie Instellingen hier. Vraag een beheerder van deze installatie.',
  },
};
